// my-gallery/models/index.js
module.exports = {
    Artwork: require('./Artwork'),
    CameraModel: require('./CameraModel'),
    Dates: require('./Dates'),
    Diptych: require('./Diptych'),
    DiptychSVG: require('./DiptychSVG'),
    Frame: require('./Frame'),
    ImageNumbers: require('./ImageNumbers'),
    Photo: require('./Photo'),
    Pricing: require('./Pricing'),
    PrintSizes: require('./PrintSizes'),
    Series: require('./Series'),
    SizeCategories: require('./SizeCategories'),
    Users: require('./Users'),
    EntityType: require('./EntityType'),
    Locations: require('./Locations'),
    PersonContactInfo: require('./PersonContactInfo'),
    OrganizationContactInfo: require('./OrganizationContactInfo'),
    Artists: require('./Artists'),
    ArtistsAdditionalPhotos: require('./ArtistsAdditionalPhotos'),
    PrivacyPreferences: require('./PrivacyPreferences'),
    AuditTrail: require('./AuditTrail'),
    PasswordResetToken: require('./PasswordResetToken'),
    Like: require('./Like'), 
    HiddenPhoto: require('./HiddenPhoto'),
  };
  